CREATE TABLE tb_chair
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id INTEGER,
    row     CHAR                                     NOT NULL,
    number  INTEGER                                  NOT NULL,
    CONSTRAINT pk_tb_chair PRIMARY KEY (id)
);

ALTER TABLE tb_chair
    ADD CONSTRAINT uc_34953ce359fc973fe51945e5a UNIQUE (room_id, row, number);

ALTER TABLE tb_chair
    ADD CONSTRAINT FK_TB_CHAIR_ON_ROOM FOREIGN KEY (room_id) REFERENCES tb_room (id);

CREATE TABLE tb_reservation
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chair_id   INTEGER                                  NOT NULL,
    user_id    UUID                                     NOT NULL,
    session_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_tb_reservation PRIMARY KEY (id)
);

ALTER TABLE tb_reservation
    ADD CONSTRAINT uc_83fb99f179855dd831ad0f54a UNIQUE (chair_id, session_id);

ALTER TABLE tb_reservation
    ADD CONSTRAINT FK_TB_RESERVATION_ON_CHAIR FOREIGN KEY (chair_id) REFERENCES tb_chair (id);

ALTER TABLE tb_reservation
    ADD CONSTRAINT FK_TB_RESERVATION_ON_SESSION FOREIGN KEY (session_id) REFERENCES tb_session (id);

ALTER TABLE tb_reservation
    ADD CONSTRAINT FK_TB_RESERVATION_ON_USER FOREIGN KEY (user_id) REFERENCES tb_user (id);

CREATE TABLE tb_room
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_tb_room PRIMARY KEY (id)
);

ALTER TABLE tb_room
    ADD CONSTRAINT uc_tb_room_name UNIQUE (name);

CREATE TABLE tb_session
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    room_id    INTEGER,
    CONSTRAINT pk_tb_session PRIMARY KEY (id)
);

ALTER TABLE tb_session
    ADD CONSTRAINT uc_cc15f0ea1e290899d56f15918 UNIQUE (start_time, end_time, room_id);

ALTER TABLE tb_session
    ADD CONSTRAINT FK_TB_SESSION_ON_ROOM FOREIGN KEY (room_id) REFERENCES tb_room (id);

CREATE TABLE tb_user
(
    id       UUID         NOT NULL,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tb_user PRIMARY KEY (id)
);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_email UNIQUE (email);